# Generated by Django 5.0 on 2023-12-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_remove_quiz_is_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-solved_date']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='chat_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='solved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
