# Generated by Django 5.0 on 2023-12-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_alter_quiz_options_quiz_chat_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz',
            field=models.TextField(blank=True),
        ),
    ]
