# Generated by Django 5.0 on 2023-12-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_quiz_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
