# Generated by Django 5.0 on 2023-12-27 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_spelling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spelling',
        ),
    ]
