# Generated by Django 5.0 on 2023-12-29 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_ocr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ocr',
        ),
    ]
