# Generated by Django 5.0 on 2023-12-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='answers',
            field=models.IntegerField(default=0),
        ),
    ]
