# Generated by Django 5.0 on 2023-12-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranking",
            name="created_dt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
