# Generated by Django 5.0 on 2023-12-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rank", "0003_alter_ranking_created_dt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranking",
            name="created_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
