# Generated by Django 5.0 on 2023-12-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0004_alter_ranking_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='user_level',
            field=models.IntegerField(default=1),
        ),
    ]
