# Generated by Django 5.0 on 2024-01-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0005_alter_ranking_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
