# Generated by Django 5.0 on 2023-12-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="introduction",
            field=models.TextField(blank=True, default="안녕하세요", null=True),
        ),
    ]
