# Generated by Django 5.0 on 2023-12-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_level',
        ),
    ]
