# Generated by Django 5.0 on 2023-12-19 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reply",
            new_name="Comment",
        ),
    ]
