# Generated by Django 5.0 on 2023-12-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_alter_comment_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/%Y/%m/%d/"
            ),
        ),
    ]
