# Generated by Django 5.0 on 2023-12-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
